version: "3.3"

services:
  next-step:
    build: .
    ports:
      - "9944:9944"
      - "9933:9933"
      - "9615:9615"
      - "30333:30333"
    
  set-in-stone:
    build: dapp/set-in-stone
    ports:
      - "80:8080"
    depends_on:
      - next-step

  polkadot-ui:
    # container_name: polkadot-ui
    image: jacogr/polkadot-js-apps:latest
    ports:
      - "8080:80"
    environment:
      WS_URL: ws://127.0.0.1:9944 
    depends_on:
      - next-step
      
  # remix:
  #   image: remixproject/remix-ide:latest
  #   ports:
  #     - "8080:80"
      